language: php

php:
  - 5.6

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

sudo: false

script: php vendor/bin/phpunit

matrix:
  fast_finish: true
